apiVersion: v1
kind: Service
metadata:
  name: seq
  namespace: ums
spec:
  selector:
    app: seq
  ports:
  - name: ingest
    port: 5341
    targetPort: 5341
  - name: ui
    port: 80
    targetPort: 80
