apiVersion: v1
kind: ConfigMap
metadata:
  name: ums-config
  namespace: ums
data:
  Seq__ServerUrl: "http://seq:5341"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"
  ConnectionStrings__kafka: "kafka:29092"
  Auth__Authority: "http://identity-api:8080"
  Auth__Audience: "api-gateway"
  Auth__RequireHttpsMetadata: "false"
  UMS__SeedTenantSlug: "ums"
  ASPNETCORE_ENVIRONMENT: "Production"
