apiVersion: v1
kind: Secret
metadata:
  name: ums-secrets
  namespace: ums
type: Opaque
stringData:
  POSTGRES_USER: "ums_user"
  POSTGRES_PASSWORD: "ums_pass_dev"
  UMS__SeedEmail: "superadmin@ums.com"
  UMS__SeedPassword: "Admin@1234"
  OpenIddict__ClientSecret: "api-gateway-secret"
  ConnectionStrings__IdentityDb: "Host=postgres;Port=5432;Database=IdentityDb;Username=ums_user;Password=ums_pass_dev"
  ConnectionStrings__AcademicDb: "Host=postgres;Port=5432;Database=AcademicDb;Username=ums_user;Password=ums_pass_dev"
  ConnectionStrings__StudentDb: "Host=postgres;Port=5432;Database=StudentDb;Username=ums_user;Password=ums_pass_dev"
  ConnectionStrings__AttendanceDb: "Host=postgres;Port=5432;Database=AttendanceDb;Username=ums_user;Password=ums_pass_dev"
  ConnectionStrings__ExaminationDb: "Host=postgres;Port=5432;Database=ExaminationDb;Username=ums_user;Password=ums_pass_dev"
  ConnectionStrings__FeeDb: "Host=postgres;Port=5432;Database=FeeDb;Username=ums_user;Password=ums_pass_dev"
  ConnectionStrings__NotificationDb: "Host=postgres;Port=5432;Database=NotificationDb;Username=ums_user;Password=ums_pass_dev"
  ConnectionStrings__FacultyDb: "Host=postgres;Port=5432;Database=FacultyDb;Username=ums_user;Password=ums_pass_dev"
  ConnectionStrings__HostelDb: "Host=postgres;Port=5432;Database=HostelDb;Username=ums_user;Password=ums_pass_dev"
